/**
 * @fileoverview AGRINEX AI — Demo Mode seed data.
 * Provides realistic data for competition demonstrations when
 * no backend is connected or Demo Mode is enabled.
 */

// ─── Demo Crops / Inventory ─────────────────────────────────────────────────

export const DEMO_CROPS = [
  {
    id: "crop-001",
    title: "Premium Basmati Rice",
    scientific_name: "Oryza sativa var. indica",
    category: "Grains & Cereals",
    description: "Export-quality long-grain basmati rice grown using sustainable farming practices in the fertile plains of Haryana. Rich aroma, low GI, certified organic.",
    quantity_available: 4200,
    unit_type: "Kg",
    production_date: "2026-04-01",
    harvest_date: "2026-05-20",
    supply_start_date: "2026-06-01",
    supply_end_date: "2026-09-30",
    shelf_life_days: 365,
    is_organic: true,
    current_stock: 4200,
    minimum_stock_alert: 500,
    status: "available" as const,
    farmer_price: 85,
    ai_recommended_price: 92,
    market_price: 88,
    market_trend: "up" as const,
    expected_demand: "high" as const,
    nearby_buyer_count: 23,
    warehouse_location: "Karnal Cold Storage, Haryana",
    storage_temp: "10–15°C",
    storage_condition: "Cool, dry place away from moisture",
    ai_quality_grade: "A+",
    ai_confidence_score: 96,
    ai_freshness_score: 94,
    ai_disease_score: 2,
    ai_pest_score: 1,
    rating: 4.9,
    reviews_count: 142,
    is_verified: true,
    certificates: ["FSSAI Certified", "Organic India", "Export Quality"],
    location: "Karnal, Haryana",
    gps_lat: 29.6857,
    gps_lng: 76.9905,
    image_url: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800",
    images: [
      "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800",
    ],
    traceability_code: "AGX-2026-HR-001",
    price_per_unit: 85,
    quality_grade: "A+",
    is_active: true,
    created_at: "2026-05-20T06:00:00Z",
  },
  {
    id: "crop-002",
    title: "Alphonso Mangoes (Hapus)",
    scientific_name: "Mangifera indica cv. Alphonso",
    category: "Fruits",
    description: "The King of Mangoes! GI-tagged Alphonso mangoes from Ratnagiri district. Naturally ripened, rich golden color, sweet and fiber-less pulp.",
    quantity_available: 800,
    unit_type: "Kg",
    production_date: "2026-04-10",
    harvest_date: "2026-05-15",
    supply_start_date: "2026-05-20",
    supply_end_date: "2026-06-30",
    shelf_life_days: 14,
    is_organic: false,
    current_stock: 800,
    minimum_stock_alert: 100,
    status: "available" as const,
    farmer_price: 320,
    ai_recommended_price: 380,
    market_price: 350,
    market_trend: "up" as const,
    expected_demand: "very_high" as const,
    nearby_buyer_count: 47,
    warehouse_location: "Ratnagiri APMC Yard",
    storage_temp: "8–12°C",
    storage_condition: "Controlled atmosphere storage, 90% humidity",
    ai_quality_grade: "A+",
    ai_confidence_score: 98,
    ai_freshness_score: 97,
    ai_disease_score: 0,
    ai_pest_score: 0,
    rating: 5.0,
    reviews_count: 89,
    is_verified: true,
    certificates: ["GI Tag – Alphonso Mango", "APEDA Export Certified"],
    location: "Ratnagiri, Maharashtra",
    gps_lat: 16.9944,
    gps_lng: 73.3120,
    image_url: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800",
    images: [
      "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800",
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=800",
    ],
    traceability_code: "AGX-2026-MH-002",
    price_per_unit: 320,
    quality_grade: "A+",
    is_active: true,
    created_at: "2026-05-15T08:00:00Z",
  },
  {
    id: "crop-003",
    title: "Organic Turmeric Fingers",
    scientific_name: "Curcuma longa",
    category: "Spices & Herbs",
    description: "High curcumin content (5.2%) turmeric fingers from Erode, the 'Turmeric City' of India. Naturally sun-dried, no artificial coloring.",
    quantity_available: 1500,
    unit_type: "Kg",
    production_date: "2026-01-15",
    harvest_date: "2026-03-01",
    supply_start_date: "2026-03-15",
    supply_end_date: "2026-12-31",
    shelf_life_days: 730,
    is_organic: true,
    current_stock: 1500,
    minimum_stock_alert: 200,
    status: "available" as const,
    farmer_price: 145,
    ai_recommended_price: 165,
    market_price: 152,
    market_trend: "stable" as const,
    expected_demand: "high" as const,
    nearby_buyer_count: 31,
    warehouse_location: "Erode Central Warehouse",
    storage_temp: "20–25°C",
    storage_condition: "Dry, dark storage. Avoid moisture.",
    ai_quality_grade: "A",
    ai_confidence_score: 94,
    ai_freshness_score: 88,
    ai_disease_score: 3,
    ai_pest_score: 2,
    rating: 4.7,
    reviews_count: 63,
    is_verified: true,
    certificates: ["NPOP Organic Certified", "Spices Board India"],
    location: "Erode, Tamil Nadu",
    gps_lat: 11.3410,
    gps_lng: 77.7172,
    image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
      "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800",
    ],
    traceability_code: "AGX-2026-TN-003",
    price_per_unit: 145,
    quality_grade: "A",
    is_active: true,
    created_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "crop-004",
    title: "Baby Spinach (Palak)",
    scientific_name: "Spinacia oleracea",
    category: "Leafy Vegetables",
    description: "Tender baby spinach grown hydroponically. Triple-washed, ready to eat. Rich in iron and vitamins. Perfect for restaurants and homes.",
    quantity_available: 200,
    unit_type: "Kg",
    production_date: "2026-06-20",
    harvest_date: "2026-06-28",
    supply_start_date: "2026-06-29",
    supply_end_date: "2026-07-10",
    shelf_life_days: 7,
    is_organic: true,
    current_stock: 200,
    minimum_stock_alert: 30,
    status: "available" as const,
    farmer_price: 60,
    ai_recommended_price: 75,
    market_price: 65,
    market_trend: "up" as const,
    expected_demand: "very_high" as const,
    nearby_buyer_count: 18,
    warehouse_location: "Pune Cold Chain Hub",
    storage_temp: "2–4°C",
    storage_condition: "Refrigerated, high humidity",
    ai_quality_grade: "A+",
    ai_confidence_score: 99,
    ai_freshness_score: 99,
    ai_disease_score: 0,
    ai_pest_score: 0,
    rating: 4.8,
    reviews_count: 34,
    is_verified: true,
    certificates: ["Hydroponic Certified", "FSSAI Grade A"],
    location: "Pune, Maharashtra",
    gps_lat: 18.5204,
    gps_lng: 73.8567,
    image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800",
    images: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800",
    ],
    traceability_code: "AGX-2026-MH-004",
    price_per_unit: 60,
    quality_grade: "A+",
    is_active: true,
    created_at: "2026-06-28T05:00:00Z",
  },
  {
    id: "crop-005",
    title: "Kesar Saffron",
    scientific_name: "Crocus sativus",
    category: "Spices & Herbs",
    description: "Premium Kashmiri Kesar saffron with ISO 3632 Grade 1 certification. Deep crimson threads with natural aroma. World's finest saffron variety.",
    quantity_available: 5,
    unit_type: "Kg",
    production_date: "2025-11-01",
    harvest_date: "2025-11-20",
    supply_start_date: "2025-12-01",
    supply_end_date: "2026-11-30",
    shelf_life_days: 1095,
    is_organic: true,
    current_stock: 5,
    minimum_stock_alert: 1,
    status: "reserved" as const,
    farmer_price: 280000,
    ai_recommended_price: 320000,
    market_price: 295000,
    market_trend: "up" as const,
    expected_demand: "high" as const,
    nearby_buyer_count: 8,
    warehouse_location: "Pampore, Kashmir — Secure Storage",
    storage_temp: "10–15°C",
    storage_condition: "Airtight glass containers, away from light",
    ai_quality_grade: "A+",
    ai_confidence_score: 97,
    ai_freshness_score: 95,
    ai_disease_score: 0,
    ai_pest_score: 0,
    rating: 5.0,
    reviews_count: 12,
    is_verified: true,
    certificates: ["GI Tag – Kashmir Kesar", "ISO 3632 Grade 1", "AGMARK Certified"],
    location: "Pampore, Jammu & Kashmir",
    gps_lat: 33.8097,
    gps_lng: 74.9910,
    image_url: "https://images.unsplash.com/photo-1607827448387-a67db820a5d6?w=800",
    images: [
      "https://images.unsplash.com/photo-1607827448387-a67db820a5d6?w=800",
    ],
    traceability_code: "AGX-2026-JK-005",
    price_per_unit: 280000,
    quality_grade: "A+",
    is_active: true,
    created_at: "2025-11-20T10:00:00Z",
  },
  {
    id: "crop-006",
    title: "Hybrid Tomatoes",
    scientific_name: "Solanum lycopersicum",
    category: "Vegetables",
    description: "Hybrid cherry tomatoes grown under net-house conditions. Bright red, uniform size, long shelf life. Perfect for salads and processing.",
    quantity_available: 180,
    unit_type: "Kg",
    production_date: "2026-05-01",
    harvest_date: "2026-06-15",
    supply_start_date: "2026-06-20",
    supply_end_date: "2026-07-20",
    shelf_life_days: 10,
    is_organic: false,
    current_stock: 180,
    minimum_stock_alert: 100,
    status: "available" as const,
    farmer_price: 45,
    ai_recommended_price: 52,
    market_price: 42,
    market_trend: "down" as const,
    expected_demand: "medium" as const,
    nearby_buyer_count: 12,
    warehouse_location: "Nashik APMC",
    storage_temp: "8–12°C",
    storage_condition: "Refrigerated, controlled atmosphere",
    ai_quality_grade: "A",
    ai_confidence_score: 91,
    ai_freshness_score: 85,
    ai_disease_score: 0,
    ai_pest_score: 0,
    rating: 4.5,
    reviews_count: 28,
    is_verified: true,
    certificates: ["FSSAI Grade A"],
    location: "Nashik, Maharashtra",
    gps_lat: 19.9975,
    gps_lng: 73.7898,
    image_url: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800",
    images: [
      "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800",
    ],
    traceability_code: "AGX-2026-MH-006",
    price_per_unit: 45,
    quality_grade: "A",
    is_active: true,
    created_at: "2026-06-15T07:00:00Z",
  },
];

// ─── Demo Orders ─────────────────────────────────────────────────────────────

export const DEMO_ORDERS = [
  {
    id: "ord-001",
    consumer: { id: "u1", full_name: "Priya Sharma", avatar_url: null, phone_number: "+91 98765 43210" },
    total_amount: 8500,
    status: "pending" as const,
    payment_status: "pending" as const,
    delivery_address: "14, Green Park Colony, New Delhi - 110016",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    order_items: [{ id: "oi-1", quantity: 100, price_at_purchase: 85, product: { id: "crop-001", title: "Premium Basmati Rice", unit_type: "Kg", image_url: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800" } }],
    tracking_history: [{ status: "pending", timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), note: "Order placed" }],
  },
  {
    id: "ord-002",
    consumer: { id: "u2", full_name: "Rahul Mehta", avatar_url: null, phone_number: "+91 87654 32109" },
    total_amount: 38400,
    status: "accepted" as const,
    payment_status: "completed" as const,
    delivery_address: "7, Marine Lines, Mumbai - 400002",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    order_items: [{ id: "oi-2", quantity: 120, price_at_purchase: 320, product: { id: "crop-002", title: "Alphonso Mangoes", unit_type: "Kg", image_url: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800" } }],
    tracking_history: [
      { status: "pending", timestamp: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(), note: "Order placed" },
      { status: "accepted", timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), note: "Accepted by farmer" },
    ],
  },
  {
    id: "ord-003",
    consumer: { id: "u3", full_name: "Anita Reddy", avatar_url: null, phone_number: "+91 76543 21098" },
    total_amount: 21750,
    status: "quality_verified" as const,
    payment_status: "completed" as const,
    delivery_address: "22, Banjara Hills, Hyderabad - 500034",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    order_items: [{ id: "oi-3", quantity: 150, price_at_purchase: 145, product: { id: "crop-003", title: "Organic Turmeric", unit_type: "Kg", image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800" } }],
    tracking_history: [
      { status: "pending", timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString() },
      { status: "accepted", timestamp: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString() },
      { status: "quality_verified", timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(), note: "AI quality verified — Grade A" },
    ],
  },
  {
    id: "ord-004",
    consumer: { id: "u4", full_name: "Kiran Joshi", avatar_url: null, phone_number: "+91 65432 10987" },
    total_amount: 4250,
    status: "dispatched" as const,
    payment_status: "completed" as const,
    delivery_address: "3, Shivaji Nagar, Pune - 411005",
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    order_items: [{ id: "oi-4", quantity: 5, price_at_purchase: 60, product: { id: "crop-004", title: "Baby Spinach", unit_type: "Kg", image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800" } }],
    tracking_history: [
      { status: "pending", timestamp: new Date(Date.now() - 76 * 60 * 60 * 1000).toISOString() },
      { status: "accepted", timestamp: new Date(Date.now() - 75 * 60 * 60 * 1000).toISOString() },
      { status: "quality_verified", timestamp: new Date(Date.now() - 74 * 60 * 60 * 1000).toISOString() },
      { status: "dispatched", timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(), note: "Dispatched via AgriNex Logistics" },
    ],
  },
  {
    id: "ord-005",
    consumer: { id: "u5", full_name: "Suresh Kumar", avatar_url: null, phone_number: "+91 54321 09876" },
    total_amount: 1260000,
    status: "delivered" as const,
    payment_status: "completed" as const,
    delivery_address: "1, Connaught Place, New Delhi - 110001",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    order_items: [{ id: "oi-5", quantity: 4.5, price_at_purchase: 280000, product: { id: "crop-005", title: "Kesar Saffron", unit_type: "Kg", image_url: "https://images.unsplash.com/photo-1607827448387-a67db820a5d6?w=800" } }],
    tracking_history: [
      { status: "pending", timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "accepted", timestamp: new Date(Date.now() - 7.5 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "quality_verified", timestamp: new Date(Date.now() - 7.2 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "dispatched", timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "delivered", timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), note: "Delivered successfully. 5★ rated." },
    ],
  },
];

// ─── Demo Analytics ───────────────────────────────────────────────────────────

export const DEMO_CHART_DATA = [
  { month: "Jan", personalEarnings: 42000, marketAverage: 38000, orders: 8, expenses: 12000 },
  { month: "Feb", personalEarnings: 58000, marketAverage: 52000, orders: 14, expenses: 14500 },
  { month: "Mar", personalEarnings: 73500, marketAverage: 61000, orders: 19, expenses: 16000 },
  { month: "Apr", personalEarnings: 89000, marketAverage: 75000, orders: 24, expenses: 18500 },
  { month: "May", personalEarnings: 124000, marketAverage: 95000, orders: 31, expenses: 22000 },
  { month: "Jun", personalEarnings: 142500, marketAverage: 108000, orders: 38, expenses: 25000 },
];

export const DEMO_SUMMARY = {
  totalEarnings: 529000,
  bagsSold: 734,
  activeListings: 5,
  trustScore: 4.9,
  farmHealthScore: 87,
  soilHealthScore: 82,
  cropHealthScore: 91,
  productivityScore: 78,
  sustainabilityScore: 85,
  profitThisMonth: 117500,
  revenueGrowth: 23.4,
  pendingOrders: 1,
  acceptedOrders: 1,
  dispatchedOrders: 1,
};

// ─── Demo Notifications ───────────────────────────────────────────────────────

export const DEMO_NOTIFICATIONS = [
  { id: "n1", title: "New Order Received 🛒", message: "Priya Sharma placed an order for 100 Kg Premium Basmati Rice worth ₹8,500", type: "order", is_read: false, created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: "n2", title: "AI Disease Alert 🌿", message: "Leaf blight risk detected in your tomato field. Apply Mancozeb 75 WP @ 2.5 g/L immediately.", type: "disease", is_read: false, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: "n3", title: "Payment Received 💰", message: "₹38,400 received for Order #ORD-002. Check your farm wallet.", type: "payment", is_read: false, created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString() },
  { id: "n4", title: "Weather Alert ⛈️", message: "Heavy rain forecast in next 48 hours in Haryana. Harvest your ready crops before it arrives.", type: "weather", is_read: true, created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString() },
  { id: "n5", title: "Low Stock Alert ⚠️", message: "Baby Spinach stock is below minimum threshold (200 Kg). Consider restocking.", type: "inventory", is_read: true, created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString() },
  { id: "n6", title: "Government Scheme 🏛️", message: "PM-KISAN 16th installment released. Check eligibility for ₹6,000 direct benefit.", type: "scheme", is_read: true, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() },
  { id: "n7", title: "Market Price Update 📈", message: "Basmati Rice prices up 8% in Delhi APMC. Best time to sell your stock!", type: "market", is_read: true, created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString() },
  { id: "n8", title: "AI Insight 🤖", message: "Your Alphonso Mangoes are rated 5★ by buyers. Consider listing 200 more Kg this week.", type: "ai", is_read: true, created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString() },
];

// ─── Demo Market Prices ───────────────────────────────────────────────────────

export const DEMO_MARKET_PRICES = [
  { crop: "Basmati Rice", mandi: "Karnal APMC", price: 88, unit: "Kg", change: +5.2, trend: "up" as const, demand: "high" as const },
  { crop: "Wheat (Sharbati)", mandi: "Hapur APMC", price: 24, unit: "Kg", change: +1.1, trend: "up" as const, demand: "medium" as const },
  { crop: "Alphonso Mango", mandi: "Ratnagiri APMC", price: 350, unit: "Kg", change: +12.5, trend: "up" as const, demand: "very_high" as const },
  { crop: "Turmeric Finger", mandi: "Erode APMC", price: 152, unit: "Kg", change: -2.3, trend: "down" as const, demand: "high" as const },
  { crop: "Onion", mandi: "Nashik APMC", price: 32, unit: "Kg", change: +18.7, trend: "up" as const, demand: "high" as const },
  { crop: "Potato", mandi: "Agra APMC", price: 18, unit: "Kg", change: -5.1, trend: "down" as const, demand: "medium" as const },
  { crop: "Tomato", mandi: "Kolar APMC", price: 28, unit: "Kg", change: +3.4, trend: "up" as const, demand: "high" as const },
  { crop: "Green Chilli", mandi: "Guntur APMC", price: 95, unit: "Kg", change: -8.2, trend: "down" as const, demand: "medium" as const },
  { crop: "Cotton", mandi: "Surendranagar APMC", price: 64, unit: "Kg", change: +2.0, trend: "stable" as const, demand: "medium" as const },
  { crop: "Soybean", mandi: "Indore APMC", price: 46, unit: "Kg", change: +0.5, trend: "stable" as const, demand: "medium" as const },
];

// ─── Demo Weather ─────────────────────────────────────────────────────────────

export const DEMO_WEATHER = {
  location: "Karnal, Haryana",
  temperature: 32,
  feels_like: 36,
  humidity: 68,
  wind_speed: 12,
  uv_index: 7,
  condition: "Partly Cloudy" as const,
  condition_icon: "⛅",
  forecast: [
    { day: "Today", high: 33, low: 24, condition: "Partly Cloudy", icon: "⛅", rain_chance: 20 },
    { day: "Tue", high: 31, low: 23, condition: "Rainy", icon: "🌧️", rain_chance: 80 },
    { day: "Wed", high: 28, low: 21, condition: "Heavy Rain", icon: "⛈️", rain_chance: 95 },
    { day: "Thu", high: 29, low: 22, condition: "Cloudy", icon: "☁️", rain_chance: 40 },
    { day: "Fri", high: 34, low: 25, condition: "Sunny", icon: "☀️", rain_chance: 5 },
    { day: "Sat", high: 36, low: 26, condition: "Hot & Sunny", icon: "🌞", rain_chance: 0 },
    { day: "Sun", high: 35, low: 25, condition: "Sunny", icon: "☀️", rain_chance: 5 },
  ],
};

// ─── Demo Farm Twin Data ──────────────────────────────────────────────────────

export const DEMO_FARM_TWIN = {
  farm_name: "Green Valley Farm",
  total_area_acres: 24.5,
  location: "Karnal, Haryana",
  crop_distribution: [
    { name: "Basmati Rice", acres: 12, percentage: 49, color: "#10b981" },
    { name: "Turmeric", acres: 6, percentage: 24, color: "#f59e0b" },
    { name: "Baby Spinach", acres: 3.5, percentage: 14, color: "#34d399" },
    { name: "Fallow Land", acres: 3, percentage: 13, color: "#475569" },
  ],
  soil_health: {
    nitrogen: 72, // %
    phosphorus: 65,
    potassium: 80,
    ph: 6.8,
    moisture: 55,
    organic_matter: 3.2,
    overall_score: 74,
  },
  water_usage: {
    this_week_liters: 124500,
    recommended_liters: 110000,
    efficiency_score: 88,
    irrigation_schedule: "Next: Today 6:00 PM — 45 minutes drip",
  },
  disease_risk: {
    overall: "Low" as const,
    zones: [
      { name: "Rice Field North", risk: "Low", score: 15, issue: null },
      { name: "Rice Field South", risk: "Medium", score: 42, issue: "Blast disease risk — monitor closely" },
      { name: "Turmeric Plot", risk: "Low", score: 18, issue: null },
      { name: "Spinach Block", risk: "Very Low", score: 8, issue: null },
    ],
  },
  harvest_prediction: {
    next_harvest_crop: "Baby Spinach",
    days_to_harvest: 4,
    expected_yield_kg: 185,
    confidence: 94,
    upcoming: [
      { crop: "Baby Spinach", days: 4, yield_kg: 185 },
      { crop: "Basmati Rice", days: 22, yield_kg: 4100 },
      { crop: "Turmeric", days: 180, yield_kg: 1450 },
    ],
  },
  yield_forecast: [
    { month: "Jul", expected: 4285, actual: null },
    { month: "Aug", expected: 820, actual: null },
    { month: "Sep", expected: 1200, actual: null },
    { month: "Oct", expected: 3100, actual: null },
    { month: "Nov", expected: 1500, actual: null },
    { month: "Dec", expected: 650, actual: null },
  ],
  profit_forecast: {
    this_month: 142500,
    next_month: 185000,
    quarter: 520000,
    year: 1840000,
  },
  carbon_score: {
    footprint_kg_co2: 2840,
    industry_average: 4200,
    sustainability_score: 82,
    green_practices: ["Drip irrigation saves 40% water", "No chemical pesticides", "Crop rotation planned"],
  },
  ai_insights: [
    { priority: "urgent", insight: "Rice blast disease risk rising in South field. Apply Tricyclazole 75WP @ 0.6g/L within 24 hours.", type: "disease" },
    { priority: "high", insight: "Alphonso Mango prices peaked at ₹380/Kg in Mumbai. Best selling window is next 3 days.", type: "market" },
    { priority: "medium", insight: "Soil phosphorus is 23% below optimal for Basmati. Apply DAP 25 Kg/acre before next irrigation.", type: "soil" },
    { priority: "low", insight: "Basmati harvest in 22 days. Book cold storage in advance to maximize shelf life and profit.", type: "harvest" },
  ],
};

// ─── Demo Reviews ─────────────────────────────────────────────────────────────

export const DEMO_REVIEWS = [
  { id: "r1", reviewer: "Priya Sharma", rating: 5, comment: "Best quality Basmati I've ever bought! Fast delivery, well-packed. Will order again!", product: "Premium Basmati Rice", date: "2026-06-25", likes: 24 },
  { id: "r2", reviewer: "Rahul Mehta", rating: 5, comment: "The Alphonso mangoes are absolutely divine. Real Ratnagiri quality!", product: "Alphonso Mangoes", date: "2026-06-20", likes: 15 },
  { id: "r3", reviewer: "Suresh Kumar", rating: 5, comment: "Genuine Kashmir saffron. Used in biryani — the color and aroma are unmatched.", product: "Kesar Saffron", date: "2026-06-18", likes: 8 },
];

// ─── Demo Government Schemes ──────────────────────────────────────────────────

export const DEMO_SCHEMES = [
  {
    name: "PM-KISAN Samman Nidhi",
    benefit: "₹6,000/year direct transfer",
    eligibility: "Small & marginal farmers",
    status: "active",
    deadline: "Ongoing",
    ministry: "Ministry of Agriculture",
  },
  {
    name: "PM Fasal Bima Yojana",
    benefit: "Crop insurance @ 2% premium",
    eligibility: "All farmers with Kisan Credit Card",
    status: "active",
    deadline: "July 31, 2026",
    ministry: "Ministry of Agriculture",
  },
  {
    name: "e-NAM (National Agriculture Market)",
    benefit: "Access to 1000+ mandis online",
    eligibility: "Registered farmers",
    status: "active",
    deadline: "Ongoing",
    ministry: "Ministry of Commerce",
  },
];

// ─── Demo Tasks ───────────────────────────────────────────────────────────────

export const DEMO_TASKS = [
  { id: "t1", title: "Apply Tricyclazole on South Rice Field", priority: "urgent" as const, done: false, due: "Today 4:00 PM" },
  { id: "t2", title: "Harvest Baby Spinach Block — 185 Kg ready", priority: "high" as const, done: false, due: "Today 6:00 AM" },
  { id: "t3", title: "Drip irrigation — Turmeric Plot", priority: "medium" as const, done: true, due: "Done 8:00 AM" },
  { id: "t4", title: "Update Alphonso price on marketplace", priority: "medium" as const, done: false, due: "Today" },
  { id: "t5", title: "Book cold storage for Basmati harvest (22 days)", priority: "low" as const, done: false, due: "This week" },
];

// ─── Demo Nearby Buyers / Warehouses ─────────────────────────────────────────

export const DEMO_NEARBY_BUYERS = [
  { id: "b1", name: "Delhi Fresh Foods Pvt. Ltd.", type: "Bulk Buyer", distance_km: 14, interested_in: ["Basmati Rice", "Turmeric"], rating: 4.8, lat: 29.7500, lng: 76.9905 },
  { id: "b2", name: "BigBasket Procurement Hub", type: "Supermarket Chain", distance_km: 28, interested_in: ["Baby Spinach", "Tomatoes"], rating: 4.9, lat: 29.6200, lng: 77.0500 },
  { id: "b3", name: "ITC Agribusiness Division", type: "Food Processing", distance_km: 35, interested_in: ["Basmati Rice", "Wheat"], rating: 4.7, lat: 29.8100, lng: 76.8200 },
  { id: "b4", name: "Reliance Retail - Farm Link", type: "Retail Chain", distance_km: 42, interested_in: ["All Fresh Produce"], rating: 4.8, lat: 29.5800, lng: 77.1200 },
];

export const DEMO_WAREHOUSES = [
  { id: "w1", name: "Karnal Cold Storage", capacity_mt: 5000, available_mt: 1200, distance_km: 3, temp_range: "0–15°C", lat: 29.6900, lng: 77.0100 },
  { id: "w2", name: "Panipat Food Processing Zone", capacity_mt: 8000, available_mt: 3500, distance_km: 22, temp_range: "2–20°C", lat: 29.3867, lng: 76.9714 },
  { id: "w3", name: "Sonipat Agri Warehouse", capacity_mt: 3500, available_mt: 800, distance_km: 48, temp_range: "5–25°C", lat: 28.9931, lng: 77.0151 },
];
